"""empty message

Revision ID: 404edb502faa
Revises: d0750604e4d3
Create Date: 2020-10-02 13:03:39.892925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '404edb502faa'
down_revision = 'd0750604e4d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_property_address', table_name='property')
    op.drop_table('property')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('address', sa.VARCHAR(length=500), nullable=True),
    sa.Column('start_date', sa.DATETIME(), nullable=True),
    sa.Column('duration', sa.INTEGER(), nullable=True),
    sa.Column('rent', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_property_address', 'property', ['address'], unique=1)
    # ### end Alembic commands ###
